from app.models import db, Book, environment, SCHEMA
import datetime

def seed_books():
  demo_book = Book(
    publisher_id = 1, title='The Prince', author= 'Niccolò Machiavelli',  price_paperback=12.50, price_hardcover=20.95, price_eBook=10.95, genre='Non-Fiction', overview= 'A timeless classic!', editorial_review= 'Continues to captivate centuries later!', publication_date= '05/29/2017', publisher= 'Fall River Press', cover_art='https://m.media-amazon.com/images/I/41r6dW8dd5L._SL500_.jpg', pages= 128)
  demo_book2 = Book(
    publisher_id = 3, title='Meditations', author= 'Marcus Aurelius',  price_paperback=9.50, price_hardcover=24.00, price_eBook=10.95, genre='Non-Fiction', overview= 'A true masterpiece!', editorial_review= 'Ancient wisdom still relevant for today.', publication_date= '02/10/1996', publisher= 'Penguin Publishing Group', cover_art='https://kbimages1-a.akamaihd.net/233196f9-1586-481b-8e71-f8d08357337b/1200/1200/False/meditations-41.jpg', pages= 304)
  demo_book3 = Book(
    publisher_id = 3,  title='Do Androids Dream of Electric Sheep?', author= 'Philip K. Dick', price_paperback=15.30, price_hardcover=24.00, price_eBook=13.99, genre='Science Fiction', overview= 'Thrilling!', editorial_review= 'Thought provoking.', publication_date= '04/26/2014', publisher= 'Random House Worlds', cover_art='https://m.media-amazon.com/images/I/41zIEWqtWYL._SX331_BO1,204,203,200_.jpg', pages= 240)
  demo_book4 = Book(
    publisher_id = 3,  title='The Godfather', author= 'Mario Puzo', price_paperback=15.99, price_hardcover=32.50, price_eBook=12.99, genre='Fiction', overview= 'With its brilliant and brutal portrayal of the Corleone family, The Godfather burned its way into our national consciousness. This unforgettable saga of crime and corruption, passion and loyalty continues to stand the test of time, as the definitive novel of the Mafia underworld.', editorial_review= 'A staggering triumph...The definitive novel about a sinister fraternity of crime.”—The Saturday Review', publication_date= '04/26/1969', publisher= 'Penguin Publishing Group', cover_art='https://prodimage.images-bn.com/pimages/9780451205766_p0_v5_s1200x630.jpg', pages= 448)
  demo_book5 = Book(
    publisher_id = 3,  title='Democracy Awakening: Notes on the State of America', author= 'Heather Cox Richardson', price_paperback=15.99, price_hardcover=30.00, price_eBook=14.99, genre='Non-Fiction', overview= "From historian and author of the popular daily newsletter LETTERS FROM AN AMERICAN, a vital narrative that explains how America, once a beacon of democracy, now teeters on the brink of autocracy — and how we can turn back.In the midst of the impeachment crisis of 2019, Heather Cox Richardson launched a daily Facebook essay providing the historical background of the daily torrent of news. It soon turned into a newsletter and its readership ballooned to more than 2 million dedicated readers who rely on her plainspoken and informed take on the present and past in America.In Democracy Awakening, Richardson crafts a compelling and original narrative, explaining how, over the decades, a small group of wealthy people have made war on American ideals. By weaponizing language and promoting false history they have led us into authoritarianism — creating a disaffected population and then promising to recreate an imagined past where those people could feel important again. She argues that taking our country back starts by remembering the elements of the nation's true history that marginalized Americans have always upheld. Their dedication to the principles on which this nation was founded has enabled us to renew and expand our commitment to democracy in the past. Richardson sees this history as a roadmap for the nation's future. Richardson's talent is to wrangle our giant, meandering, and confusing news feed into a coherent story that singles out what we should pay attention to, what the precedents are, and what possible paths lie ahead. In her trademark calm prose, she is realistic and optimistic about the future of democracy. Her command of history allows her to pivot effortlessly from the Founders to the abolitionists to Reconstruction to Goldwater to Mitch McConnell, highlighting the political legacies of the New Deal, the lingering fears of socialism, the death of the liberal consensus and birth of “movement conservatism.”Many books tell us what has happened over the last five years. Democracy Awakening explains how we got to this perilous point, what our history really tells us about ourselves, and what the future of democracy can be.", editorial_review= 'A sensational debut.”—The Saturday Review', publication_date= '04/25/2023', publisher= 'Penguin Publishing Group', cover_art='https://m.media-amazon.com/images/I/510PXreMAdL.jpg', pages= 418)
  demo_book6 = Book(
    publisher_id = 3,  title='And There Was Light: Abraham Lincoln and the American Struggle', author= 'Jon Meacham', price_paperback=22.00, price_hardcover=32.00, price_eBook=14.99, genre='Non-Fiction', overview= "A president who governed a divided country has much to teach us in a twenty-first-century moment of polarization and political crisis. Hated and hailed, excoriated and revered, Abraham Lincoln was at the pinnacle of American power when implacable secessionists gave no quarter in a clash of visions bound up with money, race, identity, and faith. In him we can see the possibilities of the presidency as well as its limitations.  At once familiar and elusive, Lincoln tends to be seen as the greatest of American presidents—a remote icon—or as a politician driven more by calculation than by conviction. This illuminating new portrait gives us a very human Lincoln—an imperfect man whose moral antislavery commitment, essential to the story of justice in America, began as he grew up in an antislavery Baptist community; who insisted that slavery was a moral evil; and who sought, as he put it, to do right as God gave him to see the right. This book tells the story of Lincoln from his birth on the Kentucky frontier in 1809 to his leadership during the Civil War to his tragic assassination in 1865: his rise, his self-education, his loves, his bouts of depression, his political failures, his deepening faith, and his persistent conviction that slavery must end. In a nation shaped by the courage of the enslaved of the era and by the brave witness of Black Americans, Lincoln's story illustrates the ways and means of politics in a democracy, the roots and durability of racism, and the capacity of conscience to shape events.", editorial_review= 'Pulitzer winner Meacham (His Truth Is Marching On) more than justifies yet another Lincoln biography in this nuanced and captivating look at the president\'s “struggle to do right as he defined it within the political universe he and his country inhabited.”', publication_date= '10/18/2022', publisher= 'Random House Publishing Group', cover_art='https://m.media-amazon.com/images/I/71X21jyuZPL.jpg', pages= 720)

  demo_book7 = Book(
    publisher_id = 3,  title='The Phantom Prince: My Life with Ted Bundy', author= 'Elizabeth Kendall,', price_paperback=13.99, price_hardcover=22.49, price_eBook=10.99, genre='True Crime', overview= "The inspiration for the five-part Amazon Original docuseries Ted Bundy: Falling for a Killer."
    "Now in paperback, this updated, expanded edition of The Phantom Prince, Elizabeth Kendall’s 1981 memoir detailing her six-year relationship with serial killer Ted Bundy, includes a new introduction and a new afterword by the author, never-before-seen photos, and a startling new chapter from the author’s daughter, Molly, who has not previously shared her story. Bundy is one of the most notorious serial killers in American history and one of the most publicized to this day. However, very rarely do we hear from the women he left behind—the ones forgotten as mere footnotes in this tragedy. The Phantom Prince chronicles Elizabeth Kendall’s intimate relationship with Ted Bundy and its eventual unraveling. As much as has been written about Bundy, it’s remarkable to hear the perspective of people who shared their daily lives with him for years. This gripping account presents a remarkable examination of a charismatic personality that masked unimaginable darkness.", editorial_review= 'It’s apparent from the very first line of The Phantom Prince to Molly’s final chapter … that Kendall’s voice, as well as that of her daughter, are needed." "Clémence Michallon"', publication_date= '10/18/2022', publisher= 'Abrams Press', cover_art='https://images-na.ssl-images-amazon.com/images/I/71Y7qq5eVGL._AC_UL210_SR210,210_.jpg', pages= 224)

  db.session.add(demo_book)
  db.session.add(demo_book2)
  db.session.add(demo_book3)
  db.session.add(demo_book4)
  db.session.add(demo_book5)
  db.session.add(demo_book6)
  db.session.add(demo_book7)
  db.session.commit()



def undo_books():
  if environment == "production":
    db.session.execute(f"TRUNCATE table {SCHEMA}.books RESTART IDENTITY CASCADE;")
  else:
    db.session.execute("DELETE FROM books")

  db.session.commit()
